MUTAG:
#  num_layers: 2
##  max_epoch: 20
#  pooling: sum
##  in_drop: 0.2 # dropout
#  drop_edge_rate: 0.2
#  beta: 0.5

PP:
#  num_hidden: 64
#  num_layers: 2
#  in_drop: 0.2

LOBSTER:
  drop_edge_rate: 0.1
#  pooling: max
#  beta: 0.5

GRID:
   drop_edge_rate: 0.2 # 11/15 mode collapse better
#   num_hidden: 64
#   max_epoch: 40
#  num_layers: 2 # worse 1106
#   mask_rate: 0.3
#  max_epoch: 0  # after setting pooling=mean -> similar result as gin-random
#  beta: 1.0
#   edge_p: 1

#   max_epoch: 200

COMMUNITY:
#    drop_edge_rate: 0.1

EGO:
#  drop_edge_rate: 0.1

PROTEINS:
   lr: 0.001 # 11/15 stable loss
   num_hidden: 64 # 11/15 lower loss
#  mask_rate: 0.1
#  in_drop: 0.2
#  drop_edge_rate: 0.0
#  beta: 0.5

ZINC:
#  num_layers: 3
#  in_drop: 0.0
#  drop_edge_rate: 0.1
#  beta: 0.5
